Lg final screen
leticiavargas/naturelle pull request #19
Opened 2023-06-09 15:57 UTC by Leticia-Guimaraes

2023-06-09 21:26 UTC, ribYuriRethink commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +    <body className="container">
Acredito que a tag body fica reservada pro corpo da página com inteiro. Aqui no caso acho que seria melhor usar uma outra tag seja semântica ou uma div mesmo.

2023-06-09 21:34 UTC, ribYuriRethink requested changes
Gostei da solução para mostrar o usuário.

2023-06-09 21:34 UTC, ribYuriRethink commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +    <body className="container">
Acredito que a tag body ficaria reservada pro corpo da página com um todo. Aqui no caso acho que seria melhor usar uma outra tag seja semântica ou uma div mesmo.

2023-06-09 21:34 UTC, ribYuriRethink commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +        <p>Seus dados foram salvos com sucesso!</p>
Aqui acho que seria interessante usar textos recebidos como propriedade no componente. Assim ele fica mais geral e pode ser reutilizado na tela de finalização de pagamentos também.

2023-06-09 21:34 UTC, ribYuriRethink commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +const RegistrationConfirmation = () => {
Exemplificando a parte de receber os textos por priedades citado mais abaixo seria: 
`({title, description})`.
Apenas um exemplo mesmo.

2023-06-09 21:47 UTC, thiagoFirsen requested changes

2023-06-09 21:47 UTC, thiagoFirsen commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +      <text className="registrationConfirmation">
Não seria melhor usar uma tag div no lugar da text? O que seria essa tag?

2023-06-09 21:47 UTC, thiagoFirsen commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +    <body className="container">
O nome da classe "container" é um pouco genérica, pode acabar dando problema com outros códigos de outras pessoas, uma vez que não estamos usando css module

2023-06-09 21:47 UTC, thiagoFirsen commented on src/components/RegistrationConfirmation/styles.css
> +.container img {
Acho que seria legal você dar um id ou uma classe para imagem, porquê pode acabar dando conflito com outras imagens que podem estar dentro de alguma classe que chama container em um outro arquivo

2023-06-10 05:48 UTC, leticiavargas commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +    <body className="container">
Sim ... a tag body e main são unicas no projeto ... e já utilizadas lá na estrutura inicial

2023-06-10 05:48 UTC, leticiavargas commented on src/components/RegistrationConfirmation/RegistrationConfirmation.jsx
> +    <body className="container">
uma sugestão é usar `final-screen-container` ... utiliza o nome do componente e a palavra container

2023-06-10 05:48 UTC, leticiavargas commented on src/components/RegistrationConfirmation/styles.css
> +}
Se optar por tornar o componente mais genérico recebendo o texto que será mostrado e assim poder utilizar na tela de pagamento ... vale repensar os nomes destas classes para também seguirem o mesmo nome genérico que o componente iria receber.

2023-06-12 15:47 UTC, thiagoFirsen approved these changes
Boaa, mandou beem

2023-06-12 15:58 UTC, ghost approved these changes
Ficou bom demais!

2023-06-12 18:28 UTC, merged