Creating Carousel Institucional component
leticiavargas/naturelle pull request #6
Opened 2023-06-02 18:07 UTC by amandacolacioRethink

Neste componente de carrosel, elementos como título e o título da imagem são opcionais. 

**- Caso não tenha título da imagem:**
      Não será renderizado um botão que cobre toda a imagem e que redireciona o usuário para a página referida.

### Modelo de informações passadas como _prop_ para o componente: 
      const data = [ 
      {url: "endereço da imagem", title: "titulo da imagem", goTo: "link para redirecionamento"},
      {url: "endereço da imagem", title: "titulo da imagem", goTo: "link para redirecionamento"}
      ]

2023-06-02 18:23 UTC, andrepfonseca commented on src/components/CarouselInstitucional/index.jsx
> +              <a href={"http://localhost:3000/" + image.goTo}>
Ressaltando que no futuro podemos refatorar essa parte do código e utilizar algum componente de uma biblioteca para realizar o redirecionamento (Link da "react router dom", por exemplo)

2023-06-02 18:23 UTC, andrepfonseca reviewed
Muito bom!! 💚

2023-06-02 21:15 UTC, arnonirethink requested changes
Galera, dá uma olhada nos comentários do código. 
Acho importante alterar: 
-o tamanho da imagem (pra não quebrar o código, como aconteceu, em caso de imagens com outras dimensões);
-Acrescentar a key=index;
-Acrescentar a propriedade image.alt pra fins de acessibilidade

O trabalho está ficando incrível! Valeu!

2023-06-02 21:15 UTC, arnoniscript commented on src/components/CarouselInstitucional/CarouselInstitucional.css
> +    font: normal 700 26px 'Roboto';
Muito massa essa forma de colocar a fonte, já com todos os atributos, parabéns <3

2023-06-02 21:15 UTC, arnoniscript commented on src/components/CarouselInstitucional/CarouselInstitucional.css
> +.image-container {
Para esta classe funcionar, precisei vincular o <code> img </code> à classe, para então dar a margem e tamanho esperados. Ficando assim
<img width="158" alt="Captura de tela 2023-06-02 162325" src="https://github.com/leticiavargas/naturelle/assets/124932698/2c882223-cfe4-44de-bd24-3f329d22e748">
<img width="199" alt="Captura de tela 2023-06-02 174435" src="https://github.com/leticiavargas/naturelle/assets/124932698/80478dee-a334-4ee2-94b9-2f77c2b8bffc">

2023-06-02 21:15 UTC, arnoniscript commented on src/components/CarouselInstitucional/CarouselInstitucional.css
> +.image-container {
Após entrar em contato com o @andrepfonseca testei o código original com a imagem vinculada pelo figma. E rodou conforme esperado. Como as imagens foram definidas pelo time de design e o componente especificamente não é replicado em outras partes do código, não vejo razão para alteração neste ponto. 
<img width="173" alt="Captura de tela 2023-06-02 175012" src="https://github.com/leticiavargas/naturelle/assets/124932698/643a9fa6-4e1b-4271-bbe3-6d6ede0b914e">

2023-06-02 21:15 UTC, arnoniscript commented on src/components/CarouselInstitucional/CarouselInstitucional.css
> +}
O componente interagiu conforme esperado. Entretanto, com o header (ainda sem review) houve uma quebra do final do roll do carousel. Provavelmente seja uma adaptação necessária no header, deixo arquivado para fins históricos. 
<img width="173" alt="Captura de tela 2023-06-02 175405" src="https://github.com/leticiavargas/naturelle/assets/124932698/0f920ca4-5a96-4b97-be60-85695f40a14f">

2023-06-02 21:15 UTC, arnonirethink commented on src/components/CarouselInstitucional/index.jsx
> +              <img src={image.url} alt={image.url} />
Para critérios de acessibilidade, é importante que o <code> alt </code> seja uma descrição real da imagem, por isso importante criar a propriedade <code> {image.alt} </code> possibilitando que ao implantar o componente os recursos de acessibilidade sejam ativados.

2023-06-02 21:15 UTC, arnonirethink commented on src/components/CarouselInstitucional/index.jsx
> +          {data && data.map((image) => (
Nesta linha, acho conveniente acrescentar a propriedade <code> index </code> para fins de performance, dando identificação única a cada elemento renderizado e evitando erros ao alterar a ordem dos elementos, por exemplo. Estabelecer a <code> key={index} </code> na div <code> image-container </code>.

2023-06-02 21:15 UTC, arnonirethink commented on src/components/CarouselInstitucional/index.jsx
> +
O código ficou incrível, parabéns galera <3

2023-06-05 15:50 UTC, andrepfonseca approved these changes

2023-06-05 15:55 UTC, arnonirethink approved these changes

2023-06-05 18:19 UTC, andrepfonseca approved these changes

2023-06-05 18:20 UTC, andrepfonseca approved these changes

2023-06-07 19:25 UTC, Juh-Sartori reviewed
parabéns galera S2

2023-06-07 19:27 UTC, merged