Build: Header and TextBody components
leticiavargas/naturelle pull request #7
Opened 2023-06-02 18:25 UTC by arnonirethink

Componente TextBody: 
Necessário colocar o texto em  <code> const text  </code> e entre <code>``</code>, chamando por <code> {text} </code> no componente. Isso foi necessário para que ele identificasse os espaços entre parágrafos e não unisse o texto. 
Exemplo: 
<code> const text = `TEXTO COM ESPAÇOS E PARÁGRAFOS`;
     [...]
app()   ........</code>
        <code> < TextBody text={text} />   </code>

Componente Header:
Existem duas classes CSS disponíveis para o título:
header-title : usada nos Headers da área Institucional
header-title-secondary : usada nos Headers da área de vitrine de produtos

Bastando alterar a classe vinculada ao título.

O alinhamento é à esquerda por critério de UX. 

<img width="348" alt="Captura de tela 2023-06-02 140408" src="https://github.com/leticiavargas/naturelle/assets/124932698/1b635d70-9217-48b2-8bc5-bbb86077a0cd">

2023-06-02 18:48 UTC, amandacolacioRethink commented on src/components/TextBody/index.jsx
> +  const paragraphs = text.split("\n\n");
Acredito que seria melhor trocar o nome dessa variável, pois vai retornar o texto com parágrafos e não só parágrafos.

Uma sugestão: textFormatted

2023-06-02 18:48 UTC, amandacolacioRethink commented on src/components/TextBody/styles.css
> +font-style: normal;
para deixar o código mais limpo podemos usar:

**font: normal 400 16px 'Roboto';** // Colocar nessa ordem para reduzir o número de linhas

2023-06-02 20:31 UTC, andrepfonseca requested changes

2023-06-02 20:31 UTC, andrepfonseca commented on src/components/TextBody/styles.css
> +font-style: normal;
E usar a extensão do prettier pra formatar o código e manter a identação!!

2023-06-02 20:31 UTC, andrepfonseca commented on src/components/TextBody/index.jsx
> +  const paragraphs = text.split("\n\n");
Mas acredito que não há necessidade de utilizar o split em "\n\n", apenas uma quebra de linha já seria necessário pra iniciar um novo paragrafo. "\n" poderia ser melhor.

2023-06-02 20:31 UTC, andrepfonseca commented on src/components/header/index.jsx
>        <div className="header-title">{title}</div>
Neste caso, é interessante receber como uma prop o tipo de header que será utilizado.
Ex: Receber como uma prop um "type" que pode receber o valor de "PRIMARY" ou "SECONDARY".
Caso seja "PRIMARY", por exemplo, o titulo ficaria centralizado.

2023-06-02 20:31 UTC, andrepfonseca commented on src/components/TextBody/index.jsx
> +        <p key={index}>{paragraph}</p>
O espaçamento dos parágrafos está de acordo com o design do figma?
Digo isto pois não encontrei nenhuma propriedade ditando o espaçamento entre paragráfos.

2023-06-05 16:09 UTC, arnonirethink commented on src/components/TextBody/index.jsx
> +        <p key={index}>{paragraph}</p>
No figma os textos da área institucional possuem dois parágrafos. Não há propriedade específica, entretanto, há a clara quebra de parágrafo, motivo pelo qual achei importante o código entender que em caso de quebra, deve reconhecê-la como tal.

2023-06-05 18:44 UTC, amandacolacioRethink commented on src/components/header/index.jsx
> +const Header = ({ title, linkback, type }) => {
O nome do componente nas pastas não está em maiúsculo. É bom deixar todos os componentes iniciando com a primeira letra em maiúsculo.

2023-06-05 18:50 UTC, andrepfonseca approved these changes
Apenas nomearia a pasta "header" para Header".

2023-06-06 12:39 UTC, leticiavargas reviewed
Coloquei dois itens pensando em um preciosismo no código, mas tá muito bom o componente de header.

2023-06-06 12:39 UTC, leticiavargas commented on src/components/TextFormatted/index.jsx
> +     e chamar na view o componente <textFormatted text={text} /> */
Muito bom ter a explicação de uso.
Apenas precisa trocar ali na tag a primeira letra que precisa ser maiuscula

2023-06-06 12:39 UTC, leticiavargas commented on src/components/TextFormatted/styles.css
> +font: normal 400 16px 'Roboto';
Aqui um preciosismo de formatação ... arrumar a identação

Colocar espaço nos itens que estão dentro da classe para mostrar que estão dentro da classe textbody

```
.textbody {
  font: ...;
  line-height ...
  ....
}
```

2023-06-06 12:41 UTC, merged